In [1]:
# import pandas as pd
# import numpy as np
# import pickle

# denoising_label_path = './denoise_results_image_ver.pkl'
# etc_label_path = './other_algo_results_image_ver.pkl'

# def open_pickle(pkl_path):
#     with open(pkl_path,'rb') as F:
#         pkl_loaded = pickle.load(F)
        
#     return pkl_loaded

# denoising_label_loaded = open_pickle(denoising_label_path)
# etc_label_loaded = open_pickle(etc_label_path)

# test_dict = {}
# for k,v in denoising_label_loaded.items():
    
#     _,data_type,label_type,_ = k.split('___')
    
#     if 'cifar' in data_type:
        
#         data_type = 'cifar'
#     elif 'mnist' in data_type:
#         data_type = 'mnist'
    
#     each_key = '___'.join(
#         [
#             data_type,
#             label_type
#         ]
#     )
#     if each_key not in test_dict.keys():
#         test_dict[each_key] = v
#     else:
#         is_test_eq= np.array_equal(
#             v,
#             test_dict[each_key]     
#         )
#         print(k,is_test_eq)
        
# for k,v in etc_label_loaded.items():
    
#     _,data_type,label_type = k.split('___')
    
#     if 'cifar' in data_type:
        
#         data_type = 'cifar'
#     elif 'mnist' in data_type:
#         data_type = 'mnist'
    
#     each_key = '___'.join(
#         [
#             data_type,
#             label_type
#         ]
#     )
#     if each_key not in test_dict.keys():
#         test_dict[each_key] = v
#     else:
#         is_test_eq= np.array_equal(
#             v,
#             test_dict[each_key]     
#         )
#         print(k,is_test_eq)



        
# with open('label_only_results_image_ver.pkl','wb') as F:
#     pickle.dump(test_dict,F)
    
# print('mission complete')
    
    
    

In [13]:
import pickle 
import numpy as np

with open('./label_only_results_image_ver.pkl','rb') as F:
    label_only_image_ver_dict = pickle.load(F)


label_ratio_lst = [round(0.1*i,1) for i in range(1,11)]
label_per_ratio_dict = {}
for k,v in label_only_image_ver_dict.items():
    
    normal_num = len(v[v == 0])
    print(normal_num,len(v[v==1]))
    label_per_ratio_dict[k] = {}
    for label_ratio in label_ratio_lst:
        
        choice_num = round(
            normal_num*label_ratio
        )
        
        print(label_ratio,choice_num)
        
        normal_idx_arr = np.where(v == 0)[0]
        
        sampled_normal_idx_arr = np.random.choice(
                normal_idx_arr,
                size=choice_num,
                replace=False
            )
        abnormal_idx_arr = np.where(
            v == 1
        )[0]
        
        filtered_idx_arr = np.sort(
            np.concatenate(
                [
                    sampled_normal_idx_arr,
                    abnormal_idx_arr
                ]
            )
        )
        
        new_key = 'normal_label_filter_ratio'+'_'+str(label_ratio)
        
        print(new_key,len(filtered_idx_arr))
        print(filtered_idx_arr)
        label_per_ratio_dict[k][new_key] = filtered_idx_arr
        
        print(v[label_per_ratio_dict[k][new_key]].shape,len(v[label_per_ratio_dict[k][new_key]][v[label_per_ratio_dict[k][new_key]]==1]),len(v[label_per_ratio_dict[k][new_key]][v[label_per_ratio_dict[k][new_key]]==0]))
        print('\n')
with open('./label_idx_arr_per_ratio_image_ver.pkl','wb') as F:
    pickle.dump(label_per_ratio_dict,F)
    
print('mission complete')
        
        
        
        
        
#     print()
        
        
        
# x = np.array([
#     i*i for i in range(1,21)
# ])   
# print(x)
# y = np.random.randint(0,10,[20])
# print(y)
# z = np.where(y>5)
# print(z)
# zz = np.sort(np.random.choice(z[0],size=5,replace=False))
# print(zz,type(zz))
# print(x[zz])

# zzz =np.where(y<=5)[0]
# print(zzz.shape)
# zzzz = np.concatenate(
#     [
#         zz,
#         zzz
#     ]
# )

# print(zzzz)
    


    
    
    

1000 9000
0.1 100
normal_label_filter_ratio_0.1 9100
[   0    1    2 ... 9997 9998 9999]
(9100,) 9000 100


0.2 200
normal_label_filter_ratio_0.2 9200
[   0    1    2 ... 9997 9998 9999]
(9200,) 9000 200


0.3 300
normal_label_filter_ratio_0.3 9300
[   0    1    2 ... 9997 9998 9999]
(9300,) 9000 300


0.4 400
normal_label_filter_ratio_0.4 9400
[   0    1    2 ... 9997 9998 9999]
(9400,) 9000 400


0.5 500
normal_label_filter_ratio_0.5 9500
[   0    1    2 ... 9997 9998 9999]
(9500,) 9000 500


0.6 600
normal_label_filter_ratio_0.6 9600
[   0    1    2 ... 9997 9998 9999]
(9600,) 9000 600


0.7 700
normal_label_filter_ratio_0.7 9700
[   0    1    2 ... 9997 9998 9999]
(9700,) 9000 700


0.8 800
normal_label_filter_ratio_0.8 9800
[   0    1    2 ... 9997 9998 9999]
(9800,) 9000 800


0.9 900
normal_label_filter_ratio_0.9 9900
[   0    1    2 ... 9997 9998 9999]
(9900,) 9000 900


1.0 1000
normal_label_filter_ratio_1.0 10000
[   0    1    2 ... 9997 9998 9999]
(10000,) 9000 1000


1000 9

In [16]:
import pickle

with open('./label_idx_arr_per_ratio_image_ver.pkl','rb') as F:
    test_dict= pickle.load(F)

for k,v in test_dict.items():
    # print(k,v)
    for kk,vv in v.items():
        print(k,kk,vv.shape)

cifar___normal_label_0 normal_label_filter_ratio_0.1 (9100,)
cifar___normal_label_0 normal_label_filter_ratio_0.2 (9200,)
cifar___normal_label_0 normal_label_filter_ratio_0.3 (9300,)
cifar___normal_label_0 normal_label_filter_ratio_0.4 (9400,)
cifar___normal_label_0 normal_label_filter_ratio_0.5 (9500,)
cifar___normal_label_0 normal_label_filter_ratio_0.6 (9600,)
cifar___normal_label_0 normal_label_filter_ratio_0.7 (9700,)
cifar___normal_label_0 normal_label_filter_ratio_0.8 (9800,)
cifar___normal_label_0 normal_label_filter_ratio_0.9 (9900,)
cifar___normal_label_0 normal_label_filter_ratio_1.0 (10000,)
cifar___normal_label_1 normal_label_filter_ratio_0.1 (9100,)
cifar___normal_label_1 normal_label_filter_ratio_0.2 (9200,)
cifar___normal_label_1 normal_label_filter_ratio_0.3 (9300,)
cifar___normal_label_1 normal_label_filter_ratio_0.4 (9400,)
cifar___normal_label_1 normal_label_filter_ratio_0.5 (9500,)
cifar___normal_label_1 normal_label_filter_ratio_0.6 (9600,)
cifar___normal_label_1 