In [1]:
import numpy as np


class class_FeatureExtractionFreq():
    
    def __init__(self):
    
        self.EPS = 1e-8
        
#         print('updated freq')
    
    def getMean(self,AmpArr):

        return np.mean(AmpArr)

    def getVarOfMean(self,AmpArr):

        return np.var(AmpArr,ddof =1)


    def getSkewnessPowerSpectrum(self,AmpArr):

        mean = np.mean(AmpArr)

        var = self.getVarOfMean(AmpArr)

        return np.mean((AmpArr-mean)**3)/((np.sqrt(var)**3))

    def getKurtosisPowerSpectrum(self,AmpArr):

        mean = np.mean(AmpArr)

        var = self.getVarOfMean(AmpArr)

        return np.mean((AmpArr-mean)**4)/((var**2))

    def getFrequencyCentre(self,FreqArr,AmpArr):

        return np.sum(FreqArr*AmpArr)/(np.sum(AmpArr))

    def getRootVar(self,FreqArr,AmpArr):

        freqCentre = self.getFrequencyCentre(FreqArr,AmpArr)

        return np.sqrt(np.mean(((FreqArr-freqCentre)**2)*AmpArr))

    def getRMS(self,FreqArr,AmpArr):

        numer = np.sum((FreqArr**2)*AmpArr)

        denom = np.sum(AmpArr)

        return np.sqrt(numer/(denom))

    def getMeanFreqOverMeanTime(self,FreqArr,AmpArr):

        numer = np.sum((FreqArr**4)*AmpArr)

        denom = np.sum((FreqArr**2)*AmpArr)

        return np.sqrt(numer/(denom))


    def getStabilisationFactor(self,FreqArr,AmpArr):

        numer = np.sum((FreqArr**2)*AmpArr)

        denom = np.sqrt(np.sum(AmpArr)*np.sum((FreqArr**4)*AmpArr))

        return numer / (denom)


    def getCoeffOfVariability(self,FreqArr,AmpArr):

        return self.getRootVar(FreqArr,AmpArr)/(self.getFrequencyCentre(FreqArr,AmpArr))


    def getSkewness(self,FreqArr,AmpArr):

        numer = np.mean(((FreqArr-self.getFrequencyCentre(FreqArr,AmpArr))**3)*AmpArr)

        denom = self.getRootVar(FreqArr,AmpArr)**3

        return numer/(denom)

    def getKurtosis(self,FreqArr,AmpArr):

        numer = np.mean(((FreqArr-self.getFrequencyCentre(FreqArr,AmpArr))**4)*AmpArr)

        denom = self.getRootVar(FreqArr,AmpArr)**4

        return numer/(denom)


    def getRMSRatio(self,FreqArr,AmpArr):

        numer = np.mean(np.sqrt(np.abs((FreqArr-self.getFrequencyCentre(FreqArr,AmpArr))))*AmpArr)
#         numer = np.mean(np.sqrt(FreqArr-self.getFrequencyCentre(FreqArr,AmpArr))*AmpArr)

        denom = np.sqrt(self.getRootVar(FreqArr,AmpArr))

        return numer/(denom)
    
    
    def getFeatureExtractionFreq(self,FreqArr,AmpArr):



        return np.array([self.getMean(AmpArr),
                         self.getVarOfMean(AmpArr),
                         self.getSkewnessPowerSpectrum(AmpArr),
                         self.getKurtosisPowerSpectrum(AmpArr),
                         self.getFrequencyCentre(FreqArr,AmpArr),
                         self.getRootVar(FreqArr,AmpArr),
                         self.getRMS(FreqArr,AmpArr),
                         self.getMeanFreqOverMeanTime(FreqArr,AmpArr),
                         self.getStabilisationFactor(FreqArr,AmpArr),
                         self.getCoeffOfVariability(FreqArr,AmpArr),
                         self.getSkewness(FreqArr,AmpArr),
                         self.getKurtosis(FreqArr,AmpArr),
                         self.getRMSRatio(FreqArr,AmpArr)
                         ])


class class_FeatureExtractionTime():
    
    def __init__(self):
    
        self.EPS = 1e-8
        
#         print('updated time')

    def getMean(self,x):

        return np.mean(x)

    def getStd(self,x):

        return np.std(x,ddof=1)

    def getSquareMeanRoot(self,x):

        sqrtedAbsX = np.sqrt(np.abs(x))

        return np.mean(sqrtedAbsX)**2


    def getRMS(self,x):

        sqaured = x*x

        meaned = np.mean(sqaured)

        sqrted = np.sqrt(meaned)

        return sqrted


    def getPeakValue(self,x):

        absX = abs(x)

        return np.max(absX)


    def getSkewness(self,x):

        meanX = np.mean(x)

        stdX = self.getStd(x)

        xMinusMeanCubic = (x-meanX)**3

        nMinusOne = len(x)-1

        return np.sum(xMinusMeanCubic)/((stdX**3)*nMinusOne)

    def getKurtosis(self,x):
        meanX = np.mean(x)

        stdX = self.getStd(x)

        xMinusMeanCubic = (x - meanX) ** 4

        nMinusOne = len(x)-1

        return np.sum(xMinusMeanCubic) / ( (stdX ** 4)*nMinusOne )

    def getCrestFactor(self,x):

        maxX = self.getPeakValue(x)
        rmsX = self.getRMS(x)

        return maxX/(rmsX)


    def getMarginFactor(self,x):

        maxX = self.getPeakValue(x)
        smrX = self.getSquareMeanRoot(x)

        return maxX/smrX 

    def getShapeFactor(self,x):

        rmsX = self.getRMS(x)
        absMeanX = self.getMeanAbsolute(x)

        return rmsX/(absMeanX)


    def getImpulseFactor(self,x):

        maxX = self.getPeakValue(x)
        absMeanX = self.getMeanAbsolute(x)

        return maxX/(absMeanX)

    def getMeanAbsolute(self,x):

        return self.getMean(abs(x))

    def getStdAbsolute(self,x):

        absX = abs(x)

        meanX = self.getMean(x)

        numer = (absX - meanX)**2

        nMinusOne = len(x)-1

        return np.sqrt(np.sum(numer)/nMinusOne)

    def getSkewnessAbsolute(self,x):

        absX = abs(x)

        meanX = self.getMean(x)

        stdX = self.getStd(x)

        numer = np.sum((absX-meanX)**3)

        nMinusOne = len(x)-1

        return numer/(nMinusOne*(stdX**3))

    def getKurtosisAbsolute(self,x):

        absX = abs(x)

        meanX = self.getMean(x)

        stdX = self.getStd(x)

        numer = np.sum((absX-meanX)**4)

        nMinusOne = len(x)-1


        return numer/(nMinusOne*(stdX**4))


    def getFeatureExtractionTime(self,x):

        return np.array([self.getMean(x), \
                        self.getStd(x), \
                        self.getSquareMeanRoot(x), \
                        self.getRMS(x), \
                        self.getPeakValue(x), \
                        self.getSkewness(x), \
                        self.getKurtosis(x), \
                        self.getCrestFactor(x), \
                        self.getMarginFactor(x), \
                        self.getShapeFactor(x), \
                        self.getImpulseFactor(x), \
                        self.getMeanAbsolute(x), \
                        self.getStdAbsolute(x), \
                        self.getSkewnessAbsolute(x), \
                        self.getKurtosisAbsolute(x)])



In [2]:

import numpy as np
import os
from itertools import repeat
from scipy import io
import matplotlib.pyplot as plt
import copy
import time
import pickle
from tqdm import tqdm
EPS = 1e-8


def doFE(arr):
    
    wayOfFE_Freq = class_FeatureExtractionFreq()
    wayOfFE_Time = class_FeatureExtractionTime()
    
    try:
        totalFEResult = []

    
        FE_result_Time = wayOfFE_Time.getFeatureExtractionTime(arr)
        
        fft_result = np.fft.fft(arr)
        fft_freq_result = np.fft.fftfreq(arr.shape[-1],1/(10*1000))
        fft_result = np.abs(fft_result*(2/len(fft_result)))

        arr_len = int(len(fft_result)/2)

        freq_arr = fft_freq_result[:arr_len]
        amp_arr = fft_result[:arr_len]

        FE_result_Freq = wayOfFE_Freq.getFeatureExtractionFreq(freq_arr,amp_arr)

        fe_result_total = np.concatenate([FE_result_Freq, FE_result_Time ])
        
            
        return fe_result_total
    
    except:
        print(f'error happened at path ')
    
    





In [8]:
# def openPickle(loadPath):
    
#     with open(loadPath, 'rb') as f:
#         data = pickle.load(f)
        
#         return data
    
# def savePickle(savePath,data):
#     with open(savePath, 'wb') as f:
#         pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
        
#     print(f'saving data into {savePath} complete')

# import numpy as np
# from copy import deepcopy

# def makeFEedData(dataType,savePath,intervalNum,noiseRatio):
    
#     assert dataType in ['800_0','800_45']
    
#     trainPath = f'./800_Testbed/pkled_data/noised_data/{dataType}_interval_{intervalNum}_noiseRatio_{noiseRatio}/trainVal_{dataType}_interval_{intervalNum}_noised_{noiseRatio}.pkl'
#     testPath = f'./800_Testbed/pkled_data/noised_data/{dataType}_interval_{intervalNum}_noiseRatio_{noiseRatio}/test_{dataType}_interval_{intervalNum}_noised_{noiseRatio}.pkl'
    
#     trainData = openPickle(trainPath)
#     testData = openPickle(testPath)
        
#     newTrainData = []
#     for eachTrainData in trainData:
        
#         data_FE_result = doFE(deepcopy(eachTrainData[0]))
        
#         newTrainData.append(
#             [
#                 data_FE_result,
#                 eachTrainData[1],
#                 eachTrainData[2]
#             ]
#         )
    
#     newTestData = []
#     for eachTestData in testData:
        
#         data_FE_result = doFE(deepcopy(eachTestData[0]))
#         # print(data_FE_result.shape)
#         newTestData.append(
#             [
#                 data_FE_result,
#                 eachTestData[1],
#                 eachTestData[2]
#             ]
#         )
        
#     os.makedirs(savePath)
   
#     savePickle(os.path.join(savePath,f'trainVal_{dataType}_interval_{intervalNum}_noised_{noiseRatio}.pkl'),newTrainData)
#     savePickle(os.path.join(savePath,f'test_{dataType}_interval_{intervalNum}_noised_{noiseRatio}.pkl'),newTestData)
    
        
# dataType_lst = ['800_0','800_45']
# interval_lst = [128]
# noiseRatio_lst = [round(i*0.1,1) for i in range(1,10)]
# # noiseRatio_lst = [0.0]
# for dataType in dataType_lst:
#     for interval_num in interval_lst:
#         for noiseRatio in noiseRatio_lst:
#             makeFEedData(
#                 dataType=dataType,
#                 savePath= f'./800_Testbed/pkled_data/FEed_data/FEed_{dataType}_interval_{interval_num}_noiseRatio_{noiseRatio}',
#                 intervalNum=interval_num,
#                 noiseRatio=noiseRatio
#             )
            
        
        

saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.1/trainVal_800_0_interval_128_noised_0.1.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.1/test_800_0_interval_128_noised_0.1.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.2/trainVal_800_0_interval_128_noised_0.2.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.2/test_800_0_interval_128_noised_0.2.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.3/trainVal_800_0_interval_128_noised_0.3.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.3/test_800_0_interval_128_noised_0.3.pkl complete
saving data into ./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.4/trainVal_800_0_interval_128_noised_0.4.pkl complete
saving data

In [10]:
# from joblib import dump, load



# def openPickle(loadPath):
    
#     with open(loadPath, 'rb') as f:
#         data = pickle.load(f)
        
#         return data
    
# def savePickle(savePath,data):
#     with open(savePath, 'wb') as f:
#         pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
        
#     print(f'saving data into {savePath} complete')

# import numpy as np
# from copy import deepcopy
# from sklearn.preprocessing import StandardScaler

# def saveScaler(dataType,savePath,intervalNum,noiseRatio):
    
#     assert dataType in ['800_0','800_45']
    
#     trainPath = f'./800_Testbed/pkled_data/FEed_data/FEed_{dataType}_interval_{intervalNum}_noiseRatio_{noiseRatio}/trainVal_{dataType}_interval_{intervalNum}_noised_{noiseRatio}.pkl'
    
#     trainData = openPickle(trainPath)
    
#     newTrainData = []
#     for eachTrainData in trainData:
#         if eachTrainData[2] == 'train':
#             newTrainData.append(
#                 eachTrainData[0]
#             )
        
        
#     newTrainData = np.stack(newTrainData)
#     print(newTrainData.shape)
#     scaler = StandardScaler()
    
#     scaler.fit(newTrainData)
    
#     dump(scaler,f'./800_Testbed/pkled_data/FEed_data/FEed_{dataType}_interval_{intervalNum}_noiseRatio_{noiseRatio}/trainVal_FEed_{dataType}_interval_{intervalNum}_noised_{noiseRatio}_scaler.joblib')
    
#     print(f'./800_Testbed/pkled_data/FEed_data/FEed_{dataType}_interval_{intervalNum}_noiseRatio_{noiseRatio}/trainVal_{dataType}_interval_{intervalNum}_noised_{noiseRatio}_mean_std.joblib', 'done')
    
    
    
    
        
# dataType_lst = ['800_0','800_45']
# interval_lst = [128,256,512,1024,2048,4096]

# noiseRatio_lst = ['0.0']
# # noiseRatio_lst = [round(i*0.1,1) for i in range(1,10)]

# for dataType in dataType_lst:
#     for interval_num in interval_lst:
#         for noiseRatio in noiseRatio_lst:
#             saveScaler(
#                 dataType=dataType,
#                 savePath= f'./800_Testbed/pkled_data/noised/FEed_{dataType}_noiseRatio_{noiseRatio}',
#                 intervalNum=interval_num,
#                 noiseRatio=noiseRatio
#             )
            
            
        

(5952, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_128_noiseRatio_0.0/trainVal_800_0_interval_128_noised_0.0_mean_std.joblib done
(2976, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_256_noiseRatio_0.0/trainVal_800_0_interval_256_noised_0.0_mean_std.joblib done
(1488, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_512_noiseRatio_0.0/trainVal_800_0_interval_512_noised_0.0_mean_std.joblib done
(744, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_1024_noiseRatio_0.0/trainVal_800_0_interval_1024_noised_0.0_mean_std.joblib done
(372, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_2048_noiseRatio_0.0/trainVal_800_0_interval_2048_noised_0.0_mean_std.joblib done
(186, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_0_interval_4096_noiseRatio_0.0/trainVal_800_0_interval_4096_noised_0.0_mean_std.joblib done
(5968, 28)
./800_Testbed/pkled_data/FEed_data/FEed_800_45_interval_128_noiseRatio_0.0/trainVal_800_45_interval_128_noised_0.0_m

In [34]:
from sklearn.preprocessing import StandardScaler

test_scaler = StandardScaler()

test_arr = np.random.randint(5,size=[3,5])

print(test_arr)
# print(test_scaler.mean_)
test_scaler.fit(test_arr)
print(test_scaler.mean_)
test_arr2 = np.random.randint(5,size=(1,5))
print(test_arr2)
test_arr2 = test_scaler.transform(test_arr2)
test_arr2 = np.flatten(test_arr2)

print(test_arr2)

[[3 3 3 0 2]
 [1 4 3 0 0]
 [3 4 2 3 2]]
[2.33333333 3.66666667 2.66666667 1.         1.33333333]
[[0 4 3 1 2]]


AttributeError: module 'numpy' has no attribute 'flatten'