In [11]:
import numpy as np 

def returnMinus(num):
    if num%2 == 0:
        return 1
    else:
        return -1

x = np.array([i*i*returnMinus(i) for i in range(10)])
print(x.shape)
print(x)

random_choice = np.random.choice([i for i in range(10)],size=5,replace=False)
mask = []
for i in range(10):
    if i in random_choice:
        mask.append(True)
    else:
        mask.append(False)
mask = np.array(mask)
print(random_choice)
print(mask)

mask2 = x ==0
print(mask2)
print(x)
print(x[mask])

(10,)
[  0  -1   4  -9  16 -25  36 -49  64 -81]
[9 0 6 8 7]
[ True False False False False False  True  True  True  True]
[ True False False False False False False False False False]
[  0  -1   4  -9  16 -25  36 -49  64 -81]
[  0  36 -49  64 -81]


In [12]:
x = np.array([i for i in range(10)])

print(x[:5])

[0 1 2 3 4]


In [23]:
num_lst = [
    947,
    474,
    237,
    118
]

ratio_lst = [1,2,4,8,16]
import random

num_to_name = {
    947 : '512',
    474 : '1024',
    237 : '2048',
    118 : '4096',
}
total_dict = {
    '512': {},
    '1024':{},
    '2048':{},
    '4096':{},
}

for num in num_lst:
    
    for ratio in ratio_lst:
        
        slice_num = round(num/ratio)
        
        random_pick = random.sample(
            [i for i in range(num)],
            slice_num
        )
        
        bool_lst = []
        for i in range(num):
            if i in random_pick:
                bool_lst.append(True)
            else:
                bool_lst.append(False)
        
        total_dict[
            num_to_name[num]
        ][ratio] = bool_lst
        
        print(total_dict[
            num_to_name[num]
        ][ratio])
        print(len(total_dict[
            num_to_name[num]
        ][ratio]))
    
    print(total_dict)
        
        
    print('----------')

import pickle  
with open('./mask_per_ratio.pkl','wb') as F:
    pickle.dump(total_dict,F)
    
print('mission_complete')

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru